'use strict';
const assert = require('node:assert/strict');
const ui = require('../webfrontend/htmlauth/assets/hostbackup.js');
assert.equal(ui.normalizeLogForDisplay('a\rb\r\nc\u001b[31md\u001b[0m'), 'a\nb\ncd');
assert.equal(ui.controlState([{type:'radio',value:'native',checked:false},{type:'radio',value:'network',checked:true}]), 'network');
assert.equal(ui.controlState([{type:'checkbox',name:'stop_targets',value:'docker:x',checked:true}]), 'docker:x');
assert.equal(ui.controlState([{type:'checkbox',name:'root_permission_ack',value:'1',checked:false}]), '0');
assert.match(ui.validateSettings({metadata_mode:'portable-archive',backup_mode:'snapshot'}), /keine inkrementellen/);
assert.match(ui.validateSettings({schedule_enabled:'1',schedule_time:'02:00',schedule_mode:'weekly',schedule_weekdays:''}), /Wochentag/);
assert.match(ui.validateSettings({schedule_enabled:'1',schedule_time:'02:00',schedule_mode:'monthly',schedule_monthdays:'1',schedule_months:''}), /Monat/);
assert.equal(ui.validateSettings({metadata_mode:'network-compatible',backup_mode:'snapshot',schedule_enabled:'1',schedule_time:'02:00',schedule_mode:'daily'}), '');
const initial={profile:'native'}, changed={}, t1=new Date(1),t2=new Date(2);
ui.updateDirty(initial,changed,'profile','network',t1);
assert.equal(changed.profile.at,t1);
ui.updateDirty(initial,changed,'profile','network',t2);
assert.equal(changed.profile.at,t1);
ui.updateDirty(initial,changed,'profile','portable',t2);
assert.equal(changed.profile.at,t2);
ui.updateDirty(initial,changed,'profile','native',t2);
assert.equal(Object.keys(changed).length,0);
assert.equal(ui.logViewport(0,500,2000),false);
assert.equal(ui.logViewport(1480,500,2000),true);
assert.equal(ui.phaseLabel('retention'),'Aufbewahrung prüfen und alte Backups bereinigen');
assert.equal(ui.phaseLabel('copying'),'copying');
assert.equal(ui.phaseLabel('selecting_sources'),'Ausgewählte Datenquellen erfassen');
assert.equal(ui.phaseLabel('future-phase'),'future-phase');
const localSources=ui.sourceSelection('{"policy":"local","overrides":{"/media/smb/allowed":true,"/media/usb/backup":false}}');
assert.equal(ui.sourceIncluded(localSources,{path:'/media/usb/data',kind:'local',selectable:true}),true);
assert.equal(ui.sourceIncluded(localSources,{path:'/media/smb/nas',kind:'network',selectable:true}),false);
assert.equal(ui.sourceIncluded(localSources,{path:'/media/smb',kind:'automount',selectable:true}),false);
assert.equal(ui.sourceIncluded(localSources,{path:'/media/smb/allowed',kind:'network',selectable:true}),true);
assert.equal(ui.sourceIncluded(localSources,{path:'/media/usb/backup/sub',kind:'local',selectable:true}),false);
assert.equal(ui.sourceIncluded(localSources,{path:'/media/smb/allowed',kind:'network',selectable:false,included:false}),false);
assert.equal(ui.sourceIncluded(ui.sourceSelection({policy:'legacy',overrides:{}}),{path:'/media/smb/nas',kind:'network',selectable:true}),true);
assert.equal(JSON.stringify(ui.sourceSelection(JSON.stringify(localSources))),JSON.stringify(localSources));
assert.throws(()=>ui.sourceSelection({policy:'local',overrides:{'/media/smb':1}}),/Ausnahme/);
const mountRows=[{path:'/mnt/nas',kind:'network',selectable:true},{path:'/mnt/nas/nested',kind:'local',selectable:true}];
assert.equal(ui.sourceIncluded(ui.sourceSelection({policy:'local',overrides:{}}),mountRows[1],mountRows),false);
assert.equal(ui.sourceIncluded(ui.sourceSelection({policy:'local',overrides:{'/mnt/nas/nested':true}}),mountRows[1],mountRows),true);
assert.equal(ui.sourceIncluded(ui.sourceSelection({policy:'local',overrides:{'/mnt':true}}),mountRows[0],mountRows),false);
assert.equal(ui.sourceIncluded(ui.sourceSelection({policy:'legacy',overrides:{'/mnt/nas':true}}),{...mountRows[0],forced_excluded:true},mountRows),false);
const autoRows=[{path:'/media/usb',kind:'automount',selectable:false},{path:'/media/usb/data',kind:'local',selectable:true},{path:'/media/usb/network',kind:'network',selectable:true}];
assert.equal(ui.sourceIncluded(ui.sourceSelection({policy:'local',overrides:{}}),autoRows[1],autoRows),true,'Known USB mount below autofs stays selected');
assert.equal(ui.sourceIncluded(ui.sourceSelection({policy:'local',overrides:{}}),autoRows[0],autoRows),false,'Autofs itself is not traversed');
assert.equal(ui.sourceIncluded(ui.sourceSelection({policy:'local',overrides:{}}),autoRows[2],autoRows),false,'Network sibling below autofs still requires explicit selection');
assert.equal(ui.sourceIncluded(ui.sourceSelection({policy:'local',overrides:{'/media/usb':false}}),autoRows[1],autoRows),false,'An explicit parent exclusion remains effective');
assert.equal(ui.sourceIncluded(ui.sourceSelection({policy:'local',overrides:{'/media/usb':false,'/media/usb/data':true}}),autoRows[1],autoRows),true,'Explicit mount selection may override a source-parent exclusion');
const remoteAutoRows=[{path:'/mnt/remote',kind:'network',selectable:true},{path:'/mnt/remote/auto',kind:'automount',selectable:false},{path:'/mnt/remote/auto/local',kind:'local',selectable:true}];
assert.equal(ui.sourceIncluded(ui.sourceSelection({policy:'local',overrides:{}}),remoteAutoRows[2],remoteAutoRows),false,'Autofs exception must not bypass an excluded network ancestor');
assert.equal(ui.sourceIncluded(ui.sourceSelection({policy:'local',overrides:{'/media/usb':true}}),autoRows[0],autoRows),false,'Autofs cannot be explicitly enabled as a whole');
const selectedAutoRows=[{path:'/outer',kind:'network',selectable:true},{path:'/outer/chosen',kind:'local',selectable:true},{path:'/outer/chosen/auto',kind:'automount',selectable:false},{path:'/outer/chosen/auto/local',kind:'local',selectable:true},{path:'/outer/chosen/auto/network',kind:'network',selectable:true}];
const selectedAuto=ui.sourceSelection({policy:'local',overrides:{'/outer':false,'/outer/chosen':true}});
assert.equal(ui.sourceIncluded(selectedAuto,selectedAutoRows[3],selectedAutoRows),true,'Selected local child starts a new inclusion branch despite older parent exclusion');
assert.equal(ui.sourceIncluded(selectedAuto,selectedAutoRows[4],selectedAutoRows),false,'Explicit local branch must not admit nested network mount');
const defaultDisplay=ui.sourceSelection({policy:'local',overrides:{}});
assert.equal(ui.sourceDisplayGroup(defaultDisplay,{path:'/',kind:'local',fstype:'overlay'}),'primary','Container root stays prominent even when it uses overlay');
for(const volume of [{path:'/boot',kind:'local',fstype:'vfat'},{path:'/media/usb/data',kind:'local',fstype:'ext4'},{path:'/media/smb/nas',kind:'network',fstype:'cifs'},{path:'/media/smb/disconnected',kind:'unmounted'},{path:'/opt/loxberry/log/plugins-data',kind:'local'},{path:'/opt/loxberry/log/plugins/user-data',kind:'local'}]) {
  assert.equal(ui.sourceDisplayGroup(defaultDisplay,volume),'primary','Real data sources and missing exceptions stay visible: '+volume.path);
}
for(const volume of [{path:'/proc',kind:'system',fstype:'proc'},{path:'/media/smb',kind:'automount',fstype:'autofs'},{path:'/var/lib/docker/overlay2/example/merged',kind:'local',fstype:'overlay'},{path:'/opt/loxberry/log/plugins',kind:'local'},{path:'/opt/loxberry/log/ramlog',kind:'local'},{path:'/opt/loxberry/log/system_tmpfs',kind:'local'}]) {
  assert.equal(ui.sourceDisplayGroup(defaultDisplay,volume),'technical','Technical mount is visually grouped: '+volume.path);
  for(const selected of [true,false]) assert.equal(ui.sourceDisplayGroup(ui.sourceSelection({policy:'local',overrides:{[volume.path]:selected}}),volume),'primary','Both selected and excluded explicit technical exceptions remain prominent');
}
const groupingRows=[{path:'/',kind:'local',fstype:'overlay',selectable:false},{path:'/proc',kind:'system',fstype:'proc',selectable:false},{path:'/media/smb',kind:'automount',fstype:'autofs',selectable:false},{path:'/media/smb/nas',kind:'network',fstype:'cifs',selectable:true},{path:'/media/usb/data',kind:'local',fstype:'ext4',selectable:true},{path:'/var/lib/docker/merged',kind:'local',fstype:'overlay',selectable:true}];
for(const selection of [defaultDisplay,ui.sourceSelection({policy:'legacy',overrides:{}}),ui.sourceSelection({policy:'local',overrides:{'/var/lib/docker/merged':false}})]) {
  const before=groupingRows.map(row=>ui.sourceIncluded(selection,row,groupingRows)), serialized=JSON.stringify(selection);
  const primary=groupingRows.filter(row=>ui.sourceDisplayGroup(selection,row)==='primary'), technical=groupingRows.filter(row=>ui.sourceDisplayGroup(selection,row)==='technical');
  assert.equal(primary.length+technical.length,groupingRows.length,'Grouping neither drops nor duplicates a mount');
  assert.equal(new Set([...primary,...technical]).size,groupingRows.length,'Every mount belongs to exactly one display group');
  assert.deepEqual(groupingRows.map(row=>ui.sourceIncluded(selection,row,groupingRows)),before,'Display grouping does not change any backup checkbox');
  assert.equal(JSON.stringify(selection),serialized,'Display grouping never changes saved exceptions');
}
const legacyNotice='Bestehende Konfiguration: bisheriger Sicherungsumfang bleibt erhalten. Fuer einen begrenzten Umfang lokale Quellen waehlen und Netzfreigaben einzeln aktivieren.';
assert.deepEqual(ui.sourceNotices([legacyNotice,'Gewählte Quelle ist nicht eingebunden.'],['Prüfung fehlgeschlagen.']),['Gewählte Quelle ist nicht eingebunden.','Prüfung fehlgeschlagen.'],'Remove only the duplicate policy explanation');
assert.deepEqual(ui.sourceNotices([], [legacyNotice]),[legacyNotice],'Errors are never filtered, even when text matches a notice');
assert.deepEqual(ui.sourceNotices(),[]);
console.log('HostBackup web behavior tests passed.');
