'use strict';
const assert = require('node:assert/strict');
const ui = require('../webfrontend/htmlauth/assets/hostbackup.js');
assert.equal(ui.normalizeLogForDisplay('a\rb\r\nc\u001b[31md\u001b[0m'), 'a\nb\ncd');
assert.equal(ui.controlState([{type:'radio',value:'native',checked:false},{type:'radio',value:'network',checked:true}]), 'network');
assert.equal(ui.controlState([{type:'checkbox',name:'stop_targets',value:'docker:x',checked:true}]), 'docker:x');
assert.equal(ui.controlState([{type:'checkbox',name:'root_permission_ack',value:'1',checked:false}]), '0');
assert.match(ui.validateSettings({metadata_mode:'portable-archive',backup_mode:'snapshot'}), /keine inkrementellen/);
assert.match(ui.validateSettings({schedule_enabled:'1',schedule_time:'02:00',schedule_mode:'weekly',schedule_weekdays:''}), /Wochentag/);
assert.match(ui.validateSettings({schedule_enabled:'1',schedule_time:'02:00',schedule_mode:'monthly',schedule_monthdays:'1',schedule_months:''}), /Monat/);
assert.equal(ui.validateSettings({metadata_mode:'network-compatible',backup_mode:'snapshot',schedule_enabled:'1',schedule_time:'02:00',schedule_mode:'daily'}), '');
const initial={profile:'native'}, changed={}, t1=new Date(1),t2=new Date(2);
ui.updateDirty(initial,changed,'profile','network',t1);
assert.equal(changed.profile.at,t1);
ui.updateDirty(initial,changed,'profile','network',t2);
assert.equal(changed.profile.at,t1);
ui.updateDirty(initial,changed,'profile','portable',t2);
assert.equal(changed.profile.at,t2);
ui.updateDirty(initial,changed,'profile','native',t2);
assert.equal(Object.keys(changed).length,0);
assert.equal(ui.logViewport(0,500,2000),false);
assert.equal(ui.logViewport(1480,500,2000),true);
console.log('HostBackup web behavior tests passed.');
